[package]
name = "gametime-common"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
